### ISSUE TITLE
You may reserve a maximum of 3 hours a week. If you are already booked for 3 hours, you cannot be placed on a waiting list on any additional reservation. Furthermore, you may not create a repeated reservation for more than 3 weeks.

### ISSUE THREAD

**Issue by arekmano** [lancelafontaine/caproomster#2]

**Comment by lancelafontaine** [comment]
I feel like this issue should probably be split into two:

1. You may reserve a maximum of 3 hours a week. If you are already booked for 3 hours, you cannot be placed on a waiting list on any additional reservation.

2. Implement repeated reservations. You may not create a repeated reservation for more than 3 weeks.

**Comment by lancelafontaine** [comment]
Involves:
1. Creation of a new Rest API and business logic
2. UI / Front-end work.

**Comment by lancelafontaine** [comment]
@Taimoorrana1 completed his part in PR #52. All that is remaining is integrating it into the REST API.
