### ISSUE TITLE
Remove 2-minute lock on room

### ISSUE THREAD

**Issue by lancelafontaine** [lancelafontaine/caproomster#20]
- Arbitrary 2 minute lock on the room will not be required in refactored implementation.
- Their implementation is buggy. It often shows that the room is occupied, when it should not be. You can tell when it refuses to accept an reservation, and this is printed on the console:
```
127.0.0.1 - - [19/Feb/2017 11:51:23] "POST /february/19 HTTP/1.1" 200 -
2016-02-19
[]
Room Occupied
```

**Comment by lancelafontaine** [comment]
Since the lock is only client-side, and we are remaking the client-side, this one will be closed as 'wont do'.

**Comment by MonsieurPetion** [comment]
ok

**Comment by lancelafontaine** [comment]
@MonsieurPetion There are still locks on rooms in the backend! Look at the `room` model in `app/core`.

**Comment by MonsieurPetion** [comment]
Closing issue done
