### ISSUE TITLE
There is a (limited) list of equipment which can be made available to any room and which you may request for the room you wish to reserve: computers, projectors, etc. This means that even if the room is available over your desired time slot, you cannot get the room if the requested equipment is not available. You will be placed on a waiting list pending availability of the equipment. Meanwhile, if the room is reserved, then you remain on the waiting list.

### ISSUE THREAD

**Issue by arekmano** [lancelafontaine/caproomster#3]
1. New mappers and table in database.
2. Core business logic and interaction with waiting lists
3. UI / Front-end work.

**Comment by adriannadiaz** [comment]
I'm taking this since there is a lot of coupling with reservation/capstone logic.

**Comment by lancelafontaine** [comment]
After discussion, we decided:
- 3 types of equipment, 3 of each type.
- Can accomplish this by adding boolean flags to Reservation
- DB changes are required in order to accommodate these changes.
