### ISSUE TITLE
Username is not validating in the login screen.

### ISSUE THREAD

**Issue by adriannadiaz** [lancelafontaine/caproomster#33]
As-is, the system is not comparing the entered username with an existing user `name` in  `usertable`. It is instead relying on the user typing in the correct `userid` and `password` of a certain entry in that table.

views.py index() performs said validation, also get rid of the redundant nested identical `return render_template('login.html',error=error)`

**Comment by lancelafontaine** [comment]
Fixed in PR #61. Closing.
