### ISSUE TITLE
What happens (on the server side) when one opens a write session on his browser, then closes the browser before the session is completed or timed-out?

### ISSUE THREAD

**Issue by arekmano** [lancelafontaine/caproomster#6]

**Comment by lancelafontaine** [comment]
Requirement not clear. Will clarify with professor

**Comment by lancelafontaine** [comment]
After discussing with professor, this requirement will not need to be implemented in the system. However, it must be explicitly rationalized in the SAD deliverable (why the removal of the lock makes for a better system, how it provides a fair system for all users, etc).
